routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return redirect() -> route('author.index');
});
Route::resource('author','AuthorController');
Route::resource('book','BookController');
Route::get('/book/create/{author}','BookController@create')->name('book.create');

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'title',
        'author_id',
        'text',
        'year'
    ];

    public function author()
    {
        return $this->belongsTo(Author::class);
    }
}

app/Http/Controllers/Api/BookController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Services\Book\BookAll;
use App\Services\Book\BookShow;
use App\Services\Book\BookUpdate;
use App\Services\Book\BookDelete;
use App\Http\Requests\BookStoreRequest;

class BookController extends Controller
{
    /**
     * Получение списка книг с именем автора
     * @param BookAll $bookAll
     * @return \Illuminate\Http\JsonResponse
     */
    public function index(BookAll $bookAll) {
        $books = $bookAll();
        return response()->json($books);
    }

    /**
     * Получение данных книги по id
     * @param BookShow $bookShow
     * @param int $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function show(BookShow $bookShow, int $id) {
        $book = $bookShow($id);
        return response() -> json($book);
    }

    /**
     * Редактирование данных книги
     * @param BookStoreRequest $request
     * @param BookUpdate $bookUpdate
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(BookStoreRequest $request,BookUpdate $bookUpdate, int $id) {
        $data = $request -> validated();
        $bookUpdate($id, $data);
        return response()->noContent();
    }

    /**
     * Удаление книги
     * @param BookDelete $bookDelete
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(BookDelete $bookDelete, int $id)
    {
        $bookDelete($id);
        return response()->noContent();
    }
}

app/Http/Controllers/BookController.php
<?php
namespace App\Http\Controllers;

use App\Services\Book\BookAll;
use App\Services\Book\BookStore;
use App\Services\Book\BookShow;
use App\Services\Book\BookUpdate;
use App\Services\Book\BookDelete;
use App\Services\Author\AuthorShow;
use App\Http\Requests\BookStoreRequest;
use Illuminate\Pagination\LengthAwarePaginator;

class BookController extends Controller
{
    private const PAGE_SLICE_COUNT = 10;

    private const PAGE_SLICE_DELIMITER = "\r\n";

    /**
     * Display a listing of the resource.
     *
     * @param BookAll $bookAll
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(BookAll $bookAll)
    {
        $books = $bookAll();
        return view('book.index', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param int $id
     * @param AuthorShow $authorShow
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create(AuthorShow $authorShow, int $id)
    {
        $author = $authorShow($id);
        return view('book.create', compact('author'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param BookStoreRequest $request
     * @param BookStore $bookStore
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(BookStoreRequest $request, BookStore $bookStore)
    {
        $data = $request -> validated();
        try {
            $book = $bookStore($data);
            return redirect()->route('book.index')->with(['bookSave' => $book]);
        } catch (\Exception $exception) {
            return redirect()->route('book.create', $data['author_id'])
                             ->with(['error' => $exception->getMessage()])
                             ->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param BookShow $bookShow
     * @param int $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(BookShow $bookShow, int $id)
    {
        $book = $bookShow($id);
        $pages = explode(self::PAGE_SLICE_DELIMITER, $book -> text);
        $paginate = new LengthAwarePaginator($pages, count($pages), self::PAGE_SLICE_COUNT);
        $paginate->setPath(route('book.show',$id));
        $current = $paginate->currentPage() * self::PAGE_SLICE_COUNT - self::PAGE_SLICE_COUNT;
        $text = $paginate->slice($current,self::PAGE_SLICE_COUNT)->implode(self::PAGE_SLICE_DELIMITER);
        return view('book.show', compact('book','text','paginate'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @param BookShow $bookShow
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(BookShow $bookShow, int $id)
    {
        $book = $bookShow($id);
        return view('book.edit', compact('book'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param BookStoreRequest $request
     * @param BookUpdate $bookUpdate
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(BookStoreRequest $request, BookUpdate $bookUpdate, $id)
    {
        $data = $request->validated();
        if (!$bookUpdate($id, $data)) {
            return redirect()->route('book.edit',$id);
        }
        return redirect()->route('book.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param BookDelete $bookDelete
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(BookDelete $bookDelete, int $id)
    {
        $bookDelete($id);
        return redirect()->route('book.index');
    }
}

resources/views/book/create.blade.php
@extends('layout')
@section('content')
    <div class="container fluid">
        <div class="row">
            <div class="col-md-auto">
                @if (session('error'))
                    <div class="alert alert-warning" role="alert">
                        {{ session('error') }}
                    </div>
                @endif
                <div class="card">
                    <div class="card-body">
                        <p class="card-text">Добавить книгу автору {{ $author -> name }}</p>
                    </div>
                </div>
                <form action="{{route('book.store')}}" method="post">
                    @csrf
                    <input type="hidden" name="author_id" value="{{ $author -> id }}">
                    <div class="form-group">
                        <label for="bookTitle">Название</label>
                        <input type="text" class="form-control" name="title" id="bookTitle" placeholder="Война и Мир">
                    </div>
                    <div class="form-group">
                        <label for="bookText">Текст</label>
                        <textarea class="form-control" id="bookText" name="text">{{ old('text') }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="bookYear">Год издания</label>
                        <input type="number" class="form-control" name="year" id="bookYear" placeholder="2010"
                               min="1800" value="2010">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn-primary">Добавить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/book/edit.blade.php
@extends('layout')
@section('content')
    <div class="container fluid">
        <div class="row">
            <div class="col-md-auto">
                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                @if (session('error'))
                    <div class="alert alert-warning" role="alert">
                        {{ session('error') }}
                    </div>
                @endif
                <form action="{{route('book.update',$book -> id)}}" method="post">
                    @method('PUT')
                    @csrf
                    <input type="hidden" name="author_id" value="{{ $book -> author_id }}">
                    <div class="form-group">
                        <label for="bookTitle">Название</label>
                        <input type="text" class="form-control" name="title" id="bookTitle" value="{{ $book -> title }}">
                    </div>
                    <div class="form-group">
                        <label for="bookText">Текст</label>
                        <textarea class="form-control" id="bookText" name="text">{{ $book -> text }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="bookYear">Год издания</label>
                        <input type="number" class="form-control" name="year" id="bookYear" value="{{ $book -> year }}" min="1800">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn-primary">Изменить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/book/index.blade.php
@extends('layout')
@section('content')
    <div class="container fluid">
        <div class="row">
            <div class="col-12">
                @if(!$books -> isEmpty())
                    <table class="table">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Название</th>
                            <th scope="col">Автор</th>
                            <th scope="col">Год</th>
                            <th scope="col">Изменить</th>
                            <th scope="col">Удалить</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($books as $book)
                            <tr>
                                <th scope="row">{{ $book -> id }}</th>
                                <td><a href="{{ route('book.show', $book -> id) }}">{{ $book -> title }}</a></td>
                                <td>
                                    <a href="{{ route('author.show', $book -> author -> id) }}">
                                        {{ $book -> author -> name }}
                                    </a>
                                </td>
                                <td>{{ $book -> year }}</td>
                                <td>
                                    <a href="{{ route('book.edit', $book->id) }}">
                                        <img src="{{asset('images/edit.png')}}">
                                    </a>
                                </td>
                                <td>
                                    <form method="post" action="{{ route('book.destroy', $book->id) }}">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="btn btn-link">
                                            <img src="{{asset('images/delete.png')}}">
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <div class="text-center">{{ $books -> links() }}</div>
                @else
                    <div class="alert alert-primary" role="alert">Данные отсутсвуют</div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/book/show.blade.php
@extends('layout')
@section('content')
    <div class="container fluid">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title text-center">{{ $book -> title }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ $book -> year }}</h6>
                <p class="card-text" style="white-space: pre-line;">{{ $text }}</p>
                <p class="text-center">{{ $paginate -> links() }}</p>
            </div>
        </div>
    </div>
@endsection