routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return redirect() -> route('author.index');
});
Route::resource('author','AuthorController');
Route::resource('book','BookController');
Route::get('/book/create/{author}','BookController@create')->name('book.create');

app/Models/Author.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Author extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name',
        'biography',
        'created_at',
        'updated_at'
    ];

    public function books() {
        return $this->hasMany(Book::class);
    }
}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use App\Services\Author\AuthorAll;
use App\Services\Author\AuthorStore;
use App\Services\Author\AuthorDelete;
use App\Services\Author\AuthorShow;
use App\Services\Author\AuthorUpdate;
use App\Http\Requests\AuthorCreate;

class AuthorController extends Controller
{
    public function index(AuthorAll $authorAll)
    {
        $authors = $authorAll();
        return view('author.index', compact('authors'));
    }

    public function create()
    {
        return view('author.create');
    }

    public function store(AuthorCreate $request, AuthorStore $authorStore)
    {
        $data = $request->validated();
        try {
            $author = $authorStore($data);
            return redirect()->route('author.index')->with(['authorSave' => $author]);
        } catch (\Exception $exception) {
            return redirect()->route('author.create')->with(['error' => $exception->getMessage()]);
        }
    }

    public function show(int $id, AuthorShow $authorShow) {
        $author = $authorShow($id);
        return view('author.show', compact('author'));
    }

    public function edit(int $id, AuthorShow $authorShow) {
        $author = $authorShow($id);
        return view('author.edit', compact('author'));
    }


    public function update(int $id, AuthorCreate $request, AuthorUpdate $authorUpdate) {
        $data = $request->only('name','biography');
        if (!$authorUpdate($id, $data)) {
            return redirect()->route('author.edit',$id);
        }
        return redirect()->route('author.index');
    }

    public function destroy(int $id, AuthorDelete $authorDelete)
    {
        $authorDelete($id);
        return redirect()->route('author.index');
    }
}

resources/views/author/create.blade.php
@extends('layout')
@section('content')
    <div class="container fluid">
        <div class="row">
            <div class="col-md-auto">
                @if (session('error'))
                    <div class="alert alert-warning" role="alert">
                        {{ session('error') }}
                    </div>
                @endif
                <form action="{{route('author.store')}}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="authorName">Имя автора</label>
                        <input type="text" class="form-control" name="name" id="authorName" placeholder="Имя Фамилия">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn-primary">Создать</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/author/edit.blade.php
@extends('layout')
@section('content')
    <div class="container fluid">
        <div class="row">
            <div class="col-md-auto">
                @if (session('error'))
                    <div class="alert alert-warning" role="alert">
                        {{ session('error') }}
                    </div>
                @endif
                <form action="{{route('author.update',$author -> id)}}" method="post">
                    @method('PUT')
                    @csrf
                    <div class="form-group">
                        <label for="authorName">Имя автора</label>
                        <input type="text" class="form-control" name="name" id="authorName" value="{{$author -> name}}">
                    </div>
                    <div class="form-group">
                        <label for="authorBio">Биография</label>
                        <textarea class="form-control" id="authorBio" name="biography" rows="3">
                            {{ $author -> biography }}
                        </textarea>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn-primary">Изменить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/author/index.blade.php
@extends('layout')
@section('content')
    <div class="container fluid">
        <div class="row">
            <div class="col-10">
                @if(!$authors -> isEmpty())
                    <table class="table">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Имя</th>
                            <th scope="col">Кол-во книг</th>
                            <th scope="col">Добавлен</th>
                            <th scope="col">Изменить</th>
                            <th scope="col">Удалить</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($authors as $author)
                            <tr>
                                <th scope="row">{{ $author -> id }}</th>
                                <td><a href="{{ route('author.show', $author -> id) }}">{{ $author -> name }}</a></td>
                                <td>{{ $author -> books_count }}</td>
                                <td>{{ $author -> created_at }}</td>
                                <td>
                                    <a href="{{ route('author.edit', $author->id) }}">
                                        <img src="{{asset('images/edit.png')}}">
                                    </a>
                                </td>
                                <td>
                                    <form method="post" action="{{ route('author.destroy', $author->id) }}">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="btn btn-link">
                                            <img src="{{asset('images/delete.png')}}">
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <div class="text-center">{{ $authors -> links() }}</div>
                @else
                    <div class="alert alert-primary" role="alert">Данные отсутсвуют</div>
                @endif
            </div>
            <div class="col-2">
                <div class="form-group">
                <a class="btn btn-primary" href="{{route('author.create')}}">Добавить автора</a>
                </div>
                @if (session('authorSave'))
                    <div class="alert alert-success" role="alert">
                        Автор добавлен
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/author/show.blade.php
@extends('layout')
@section('content')
    <div class="container fluid">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ $author -> name }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Биография</h6>
                        <p class="card-text">{{ $author -> biography }}</p>
                        <a href="{{ route('book.create', $author -> id) }}" class="card-link">Добавить книгу</a>
                    </div>
                </div>
    </div>
@endsection